# http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: required
dist: trusty

# http://docs.travis-ci.com/user/languages/javascript-with-nodejs/
language: node_js
node_js:
  - "8"
  - "9"
  - "10"
  - "11"
  - "12"

install:
  - npm install

before_script:
  - echo '{"type":"service_account"}' > client_secret.json
  - npm run lint

# http://docs.travis-ci.com/user/pull-requests/
script:
  - CLIENT_SECRET_PATH='./client_secret.json' LOCAL_PACKAGE_PATH='../' TESTS_FOLDER_PATH='./tests' npm test
